### ISSUE TITLE
RxJava 1.x now EOL

### ISSUE THREAD

**Issue by chetanmeh** [Azure/azure-cosmosdb-java#28]
As per [RxJava 1.x Readme](https://github.com/ReactiveX/RxJava/tree/1.x#end-of-life-notice) its marked as EOL 

> As of March 31, 2018, The RxJava 1.x branch and version is end-of-life (EOL). No further development, bugfixes, documentation changes, PRs, releases or maintenance will be performed by the project on the 1.x line.

Currently this project uses 1.3.3 version. Given the EOL are there any plans to switch to 2.x series?

### RxNetty

RxNetty version being used is 0.4.2. Currently there is no release of RxNetty and as per [current status](https://github.com/ReactiveX/RxNetty#project-status)

> 1.0.x will be the RxNetty-2 update. It is currently pending an RFC for API changes. 

PS: Did not found any link to forum. So posting this question as issue. Let me know  if there is any user forum where such queries can be posted

**Comment by moderakh** [comment]
@chetanmeh RxNetty-2 will be based on RxJava2. We are doing active development and we will have support for RxJava2.

**Comment by zhouchong90** [comment]
@moderakh Will you support Reactor interface (Flux and Mono) as well in the new updates? Or only RxJava2 will be supported. Is there any plan to support the Repository pattern for the reactive APIs?

**Comment by moderakh** [comment]
@vimalnelson will do RxJava2 early 2019.

**Comment by iteration21** [comment]
Can you share ETA on RxJava2 upgrade

**Comment by moderakh** [comment]
@chrisanderson

**Comment by moderakh** [comment]
@christopheranderson

**Comment by christopheranderson** [comment]
We do have a plan locked down for this now. 🎉

We'll be moving to Reactor instead of RxJava2 based on feedback from lots of folks that Reactor is a bit more future proof and it needed anyway for a lot of Spring stuff we need. This appears to be the direction that the rest of the Azure SDKs are going as well, though I can't speak for anything other than Cosmos DB SDKs.

📅 We plan on having a preview of that in a month or two.

📅 We plan on having a GA release a month or two after that preview.

(Disclaimer: These dates are based on best guesses + some buffer, but we are quality driven and they may change)

P.S. - we're in the process of moving all our development to GitHub instead of our current mirroring process. This will allow y'all to see and provide feedback on the Reactor based APIs while they are development. Once we've moved to GitHub, I'll try to remember to update this thread.

P.P.S - If RxJava2 is a must vs Reactor, please reach out to me chrande (at) microsoft (dot) com. Would love to understand scenarios where it wouldn't work for y'all (and share with our broader SDK teams on Azure).

**Comment by zhouchong90** [comment]
Reactor is great! It has great support by Springboot 2.0 :D Thank you so much for doing this. 
One more question, could you provide support after this package to integrate with spring-data-cosmosdb? And support some queries like 
Mono<User> findById(String id);

**Comment by christopheranderson** [comment]
We are in fact adding spring-data-cosmosdb integration.

We released azure-cosmosdb 3.0.0-beta-2 to Maven, btw: https://mvnrepository.com/artifact/com.microsoft.azure/azure-cosmosdb/3.0.0-beta-2

So we're ready for feedback on the new Reactor based SDK. It also changes the OM around significantly to move away from needing to generate URL strings/etc. We'll be doing further coding on the `v3` branch until we're ready to GA it and then we'll merge to `master`.

I'm working on a detailed "what changed" guide that I'll post probably next week.

**Comment by christopheranderson** [comment]
Done in V3
